version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment: # node 환경변수 주입. 따로 .env 파일을 작성할 필요 없이 여기다 환경변수 값들을 셋팅할 수도 있다.
      DATABASE_USERNAME: jihokim
      DATABASE_PASSWORD: '21413784'
      DATABASE_TYPE: postgres
      DATABASE_HOST: localhost # 호스트 이름은 services 하의 데이터베이스 이름과 같아야 한다.
      DATABASE_PORT: 5432
      DATABASE_DATABASE: buildnow_test
      DATABASE_SYNCHRONIZE: true
      PORT: 3000
