version: '24.0'
services:
  app:
    build: .
    ports:
      - "3000:3000"

    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ji-hokim
      POSTGRES_PASSWORD: 21413784
      POSTGRES_DB: buildnow_test
    ports:
      - "5432:5432"
