version: '24.0'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      RDS_HOSTNAME: localhost
    depends_on:
      - localhost
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ji-hokim
      POSTGRES_PASSWORD:
      POSTGRES_DB: buildnow_test
    ports:
      - "5432:5432"
