version: '24.0'
services:
  app:
    image: "node:21"
    working_dir: /usr/src/app
    environment: # node 환경변수 주입. 따로 .env 파일을 작성할 필요 없이 여기다 환경변수 값들을 셋팅할 수도 있다.
      DB_USER: ji-hokim 
      DB_PWD: 21413784
      DB_TYPE: postgres
      DB_HOST: pg # 호스트 이름은 services 하의 데이터베이스 이름과 같아야 한다. 
      DB_PORT: 5432
      DB_NAME: buildnow_test
    volumes:
      - ./src:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - pg
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: ji-hokim
      POSTGRES_PASSWORD: 21413784
      POSTGRES_DB: buildnow_test
    ports:
      - "5432:5432"
